### ISSUE TITLE
Querying by column values?

### ISSUE THREAD

**Issue by alvaro1728** [alexisrolland/flask-graphene-sqlalchemy#7]
Thanks for this great tutorial. I only wish it would have shown how to query the data by specific column values. For example, show me a planet of a given name or all the planets with gravity > X.

Regards,
Alvaro

**Comment by alexisrolland** [comment]
Hi @alvaro1728 
Indeed these are important features of GraphQL. I personnally stopped to use Flask/Graphene and switched most of my projects to PostgreSQL and PostGraphile which automatically generates a feature complete GraphQL API. It includes in particular the features you mentioned above and even more. You should check this other tutorial ;) https://github.com/alexisrolland/docker-postgresql-postgraphile
